version: "3.9"

services:
  icsmw:
    image: skorpil/icsmw:dev
    labels:
      - "traefik.http.routers.frontend.tls.certresolver=local"
    environment:
      NODE_ENV: development
    build:
      target: dev
    volumes:
      - ./application:/srv
